# an example docker-compose.yml for a fully functional montesquieu+postgres stack
# before running execute scripts/docker-build.sh and scripts/docker-compose-prepare.sh
version: '2'
services:
  montesquieu:
    image: montesquieu
    restart: unless-stopped
    depends_on:
      - postgres
    ports:
      - '80:80'
    environment:
      # change these
      BLOGNAME: "replace with your own blog name"

      # these don't need to be changed, but feel free to modify them
      ARTICLESPERPAGE: 5
      LISTENON: ":80"

      # dont change these, unless you know what you're doing
      # you can also use the "mock" store, which does almost nothing
      # postgres currently does nothing too, but it at least pretends it's useful
      STORE: "postgres"
      STORE_HOST: "localhost"
      STORE_DB: "montesquieu"
      STORE_USER: "montesquieu"
      STORE_PASSWORD: "montesquieu"
      CACHINGSTORE: "off"
      HOTSWAPTEMPLATES: "no"

  postgres:
    image: postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: montesquieu
      POSTGRES_PASSWORD: montesquieu
    volumes:
      - ./docker-data/postgres:/var/lib/postgresql/data

